### ISSUE TITLE
`classroom` missing `uai` column

### ISSUE THREAD

**Issue by quentint** [vittascience/OpenSTEAM-LMS#52]
Apparently the `classroom` table is missing the `uai` column:

https://github.com/vittascience/OpenSTEAM-LMS/blob/0c402073c4e97afe5a37388d4ec2ca8b27850fcf/sql-files/steam-lms-generate-db.sql#L31-L39

That makes it incompatible with the Classroom entity and fails on `INSERT` with `Column not found: 1054 Unknown column 'uai' in 'field list'`:

https://github.com/vittascience/vclassroom/blob/e6742979f64dc620c827dcd502dfe10e486fda60/src/Entity/Classroom.php#L56-L60

**Comment by ultimecreation** [comment]
Hello quentint, we updated the updated the "steam-lms-generate-db.sql". Now the uai field is included
